//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVV.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VVV.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string AcceptedRequestDeleted {
            get {
                return ResourceManager.GetString("AcceptedRequestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;U heeft een nieuw verlofverzoek&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family:Verdana; font-size: 12px; color: #000;&quot;&gt;
        ///    &lt;p&gt;
        ///        Beste &lt;!--NaamManager--&gt;
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        &lt;!--NaamMedewerker--&gt; heeft een nieuw verlofverzoek bij u ingelegd.
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Dit verlofverzoek heeft als reden: &lt;!--RedenVerlofverzoek--&gt;.
        ///        &lt;br /&gt;
        ///        De verlofperi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewVacationRequestManager {
            get {
                return ResourceManager.GetString("NewVacationRequestManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;VerlofVerzoek geaccepteerd&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family:Verdana; font-size: 12px; color: #000;&quot;&gt;
        ///    &lt;p&gt;
        ///        Geachte heer, mevrouw,
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Het volgende verzoek is geaccepteerd door uw manager:
        ///        &lt;br /&gt;
        ///        Reden:&lt;br/&gt;
        ///        &lt;!--Reason--&gt;&lt;br/&gt;&lt;br /&gt;
        ///        In de periode van:&lt;br /&gt;
        ///        &lt;!--BeginDate--&gt; t/m &lt;!--EndDate--&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestAccepted {
            get {
                return ResourceManager.GetString("RequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;VerlofVerzoek geaccepteerd&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family:Verdana; font-size: 12px; color: #000;&quot;&gt;
        ///    &lt;p&gt;
        ///        Geachte heer, mevrouw,
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Het volgende verzoek is geaccepteerd, het betreft de medewerker &lt;!--User--&gt;:
        ///        &lt;br /&gt;
        ///        Reden:&lt;br /&gt;
        ///        &lt;!--Reason--&gt;&lt;br /&gt;&lt;br /&gt;
        ///        In de periode van:&lt;br /&gt;
        ///        &lt;!--BeginDate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestAcceptedManager {
            get {
                return ResourceManager.GetString("RequestAcceptedManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;VerlofVerzoek afgewezen door uw manager&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family:Verdana; font-size: 12px; color: #000;&quot;&gt;
        ///    &lt;p&gt;
        ///        Geachte heer, mevrouw,
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Het volgende verzoek is afgewezen door uw manager:
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Reden van afwijzing:&lt;br /&gt;
        ///        &lt;!--ReasonRejection--&gt;
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Reden van het verlofv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestRejected {
            get {
                return ResourceManager.GetString("RequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;VerlofVerzoek afgewezen door uw manager&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family:Verdana; font-size: 12px; color: #000;&quot;&gt;
        ///    &lt;p&gt;
        ///        Geachte heer, mevrouw,
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Het volgende verzoek is afgewezen, het betreft de medewerker &lt;!--User--&gt;:
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Reden van afwijzing:&lt;br /&gt;
        ///        &lt;!--ReasonRejection--&gt;
        ///        &lt;br /&gt;&lt;br /&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestRejectedManager {
            get {
                return ResourceManager.GetString("RequestRejectedManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Wachtwoord resetten&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family: Verdana; font-size: 12px; color: #000;&quot;&gt;
        ///    &lt;p&gt;
        ///        Geachte heer, mevrouw,
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        U bent aangemeld bij de KEMBIT tool: De Verlofverzoekverwerker. Deze tool wordt gebruikt binnen het bedrijf om het verlof aan te vragen en te beoordelen.
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Voordat u met deze tool aan de slag kunnen, moet u eerst uw wachtwoor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResetFirstPassword {
            get {
                return ResourceManager.GetString("ResetFirstPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Wachtwoord resetten&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family: Verdana; font-size: 12px; color: #000;&quot;&gt;
        ///    &lt;p&gt;
        ///        Geachte heer, mevrouw,
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Wilt u uw wachtwoord wijzigen?
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Klik op deze &lt;!--link--&gt; om uw wachtwoord te veranderen. Deze link blijft &lt;!--validityinminutes--&gt; minuten geldig.
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Met vriendelijke groet,
        ///        &lt;br /&gt;&lt;br /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Wachtwoord gereset&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family: Verdana; font-size: 12px; color: #000;&quot;&gt;
        ///    &lt;p&gt;
        ///        Geachte heer, mevrouw,
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Uw wachtwoord is aangepast. Klik op deze &lt;!--link--&gt; om opnieuw in te loggen.
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Met vriendelijke groet,
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        VerlofVerzoekVerwerker
        ///    &lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Welkom bij de VerlofVerzoekVerwerker&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family:Verdana; font-size: 12px; color: #000;&quot;&gt;
        ///    &lt;p&gt;
        ///        Geachte heer, mevrouw,
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        U bent door uw HR-afdeling geregistreerd bij de VerlofVerzoekVerwerker.
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Deze tool wordt binnen Kembit gebruikt voor het regelen van Verlof.
        ///        &lt;br /&gt;&lt;br /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
